# -*- coding: utf-8 -*-
"""deepa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycpbUUbIYYc5o-Pj7PtJo6Ec9ZL8uXhS
"""

import pandas as pd
import numpy as np
import streamlit as st
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
df=pd.read_csv("C:/Users/CS-04/Documents/placement1.csv")
print(df)
print(df.isnull().sum())

x=df.iloc[:,[-2]].values
y=df.iloc[:,[-1]].values
print(x.shape,y.shape)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train,x_test,y_train,y_test)

lr=LinearRegression()
lr.fit(x_train,y_train)

y_predict=lr.predict(x_test)
print(y_predict)

train_accuracy=lr.score(x_train,y_train)
test_accuracy=lr.score(x_test,y_test)
print(train_accuracy)
print(test_accuracy)

cgpa = st.text_input("ENTER YOUR CGPA")
if st.button("package predict"):
    try:
        cgpa = float(cgpa)
        if cgpa < 0 or cgpa > 10:
            st.error("please enter a valid CGPA between 0 and 10.")
        else:
            prediction=lr.predict(np.array([[cgpa]]))
            st.success(f"package predict : {prediction[0][0]:.2f} LPA")
    except ValueError:
        st.error("please enter a valid number for CGPA.")

